# Generated by Django 4.1.3 on 2023-01-04 13:53

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('calendarID', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('isPersonal', models.BooleanField(default=False)),
                ('isAnonymous', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('journalID', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('entryID', models.TextField(primary_key=True, serialize=False)),
                ('journalID', models.TextField()),
                ('author', models.TextField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.TextField(blank=True, primary_key=True, serialize=False, unique=True)),
                ('title', models.TextField()),
                ('isAllday', models.BooleanField()),
                ('start', models.TextField()),
                ('end', models.TextField()),
                ('category', models.TextField()),
                ('dueDateClass', models.TextField(blank=True)),
                ('location', models.TextField(blank=True)),
                ('state', models.TextField()),
                ('isPrivate', models.BooleanField()),
                ('tag', models.TextField(blank=True)),
                ('owner', models.TextField()),
                ('attendee', models.TextField()),
                ('calendarID', models.ManyToManyField(to='SharedCalendar.calendar')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendarID', models.TextField()),
                ('user', models.TextField()),
                ('color', models.TextField()),
            ],
            options={
                'unique_together': {('calendarID', 'user')},
            },
        ),
        migrations.AddField(
            model_name='calendar',
            name='journals',
            field=models.ManyToManyField(blank=True, to='SharedCalendar.journal'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
