# Generated by Django 4.1.3 on 2022-12-06 14:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('calendarId', models.TextField()),
                ('id', models.TextField(blank=True, primary_key=True, serialize=False, unique=True)),
                ('title', models.TextField()),
                ('isAllday', models.BooleanField()),
                ('start', models.TextField()),
                ('end', models.TextField()),
                ('category', models.TextField()),
                ('dueDateClass', models.TextField(blank=True)),
                ('location', models.TextField(blank=True)),
                ('state', models.TextField()),
                ('isPrivate', models.BooleanField()),
                ('tag', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('calendarID', models.TextField(blank=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
