# Generated by Django 4.1.3 on 2022-11-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SharedCalendar',
            fields=[
                ('calendarId', models.TextField()),
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('title', models.TextField(default=True)),
                ('isAllday', models.BooleanField()),
                ('start', models.TextField()),
                ('end', models.TextField()),
                ('category', models.TextField()),
                ('dueDateClass', models.TextField()),
                ('location', models.TextField()),
                ('state', models.TextField()),
                ('isPrivate', models.BooleanField()),
            ],
        ),
    ]
