# Generated by Django 4.1.3 on 2022-12-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SharedCalendar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('calendarId', models.TextField()),
                ('id', models.TextField(blank=True, primary_key=True, serialize=False, unique=True)),
                ('title', models.TextField()),
                ('isAllday', models.BooleanField()),
                ('start', models.TextField()),
                ('end', models.TextField()),
                ('category', models.TextField()),
                ('dueDateClass', models.TextField(blank=True)),
                ('location', models.TextField(blank=True)),
                ('state', models.TextField()),
                ('isPrivate', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('saltedPassword', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='SharedCalendar',
        ),
    ]
