# Generated by Django 4.1.3 on 2022-12-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SharedCalendar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendarID', models.TextField()),
                ('user', models.TextField()),
                ('color', models.TextField()),
            ],
            options={
                'unique_together': {('calendarID', 'user')},
            },
        ),
    ]
