# Generated by Django 4.1.3 on 2023-01-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SharedCalendar', '0002_remove_journalentry_entryid_journalentry_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='id',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='entryID',
            field=models.TextField(default='', primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
